build-bubble-sort:
	@g++ bubble-sort.cpp -o bin/bubble-sort

run-bubble-sort:
	@./bin/bubble-sort

build-insertion-sort:
	@g++ insertion-sort.cpp -o bin/insertion-sort

run-insertion-sort:
	@./bin/insertion-sort

build-selection-sort:
	@g++ selection-sort.cpp -o bin/selection-sort

run-selection-sort:
	@./bin/selection-sort
